apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-k8s-app
  template:
    metadata:
      labels:
        app: docker-k8s-app
    spec:
      containers:
      - name: flask-app
        image: dockerryuu/docker-k8s-app:latest
        ports:
        - containerPort: 5001
